### ISSUE TITLE
Does this verifiably interoperate with Apple / Google Contact Tracing?

### ISSUE THREAD

**Issue by marcdownie** [oseiskar/corona-sniffer#3]
Does the crypto in this repository verifiably interoperate with RPIs generated from TEKs/ Diagnosis Keys captured over-the-air from Apple's implementation? 

We have TEKs and RPIs captured this way, but are so far unable to successfully generate the RPIs we've captured from the TEKs disclosed by Apple's implementation. 

We're happy to provide keys / traces if this would help you.

**Comment by oseiskar** [comment]
I have not had access to the Google/Apple implementation yet so I have not been able to verify this. I have only verified interoperability with DP-3T. It would be great if you can send me TEKs and RPIs (e.g. to this ticket or my email address you can find in my profile) so I can check if they match what I though they should be according to the spec, and tweak the crypto in this repo if not.

**Comment by marcdownie** [comment]
Here are some RPIs we sniffed that are purportedly from A2469729B173B8D69F87D51BD9D6D06B, starting at rollingStartNumber= 2647728 (e.g May 4th 7pm CDT -> May 5th 7pm CDT)

[run1_capture.txt](https://github.com/oseiskar/corona-sniffer/files/4623374/run1_capture.txt)

From our _two_ independent implementations of the crypto, and this one we found here here : https://github.com/phooky/contact-tracing-ble, we get the following keys:

```
ad82097611ef23dc4cfaf9d076edacee
3428d09259788c1afe3deda63677ab64
25c32f20651b5ead8625020600a06e60
...
```
Scanning for any of those are prefixes in the captured set we find none!

I just ran your cryptographay.js and, to save you the bother, you get the same RPIs as we do. We're either all wrong in the same way, I'm writing the TEK wrong, Apple is wrong, or Apple's code is lying (at the moment). 

We've updated our test devices to the very latest beta (the one _after_ the exposure notification update) to see if this changes the over-the-air-behavior. We have to wait a day (Diagnosis Keys for the current day are not available until after the day's end, which ends in 7 hours) to test against a new Diagnosis Key.

**Comment by oseiskar** [comment]
Thanks, very interesting. I could not figure out what's wrong either. The keys in `run1_capture.txt` are actually RPI+AEM (since they're 20 bytes long), but that does not seem to be the issue. I tried to generate the RPIs for that TEK for the rather extended UNIX time range `{ timeBegin: 0, timeEnd: 2453391426 }` -> no matches

**Comment by oseiskar** [comment]
One thing you could try for extra verification is to check if you get the same RPIs from [your scanner code](https://github.com/phooky/contact-tracing-ble/blob/master/bt.cpp) and my [crude Linux BLE scanner](https://github.com/oseiskar/corona-sniffer/blob/master/linux/ble_scan.py) (which it just reads and parses the `hcidump` string output)

**Comment by marcdownie** [comment]
I imagine we do; we have a CoreBluetooth scanner running on macOS, a hcidump based scanner on a Raspberry Pi, and hcidump scanner on Desktop / Ubuntu and have even eyeballed the data once on Android. It's all the same stuff. 

We've just finished a longer trawl through our logs and _most bizzarely_ we have an RPI that's successfully generated from "our" code in our logs. But _only one_. 

TEK / Diagnosis Key = `C32BDCEC2CC4811BE1B412FCDAE37DB4`
Rolling Period for the key starts at = 2648736
At interval number `2648736 + 143` (i.e the _very last one_ before the new TEK arrives) we see `8087fcc42f8e0b9c9a496245c4da72531a7a1b6d` over the air for a period of time between May 12 18:56:25 CDT and May 12 19:17:40 CDT (the last 4 bytes are the encrypted metadata)

Several things are odd about this. 

1. Firstly, why only one? We're generating and searching +/- 10000 intervals around each validity period on each TEK. Even if we miss the occasional RPI over the air, we'd expect to match most of the 144 in any given period. The device is sitting next to the bluetooth scanner.

2. Secondly, the times are slightly off. Unless there's something about unix epoch time that I don't know, period 143 should be between May 12 18:50:00 and 19:00:00. The rolling period is too late (by 6mins) and too long (by a factor of ~2.5).

**Comment by oseiskar** [comment]
Very peculiar. That really starts to sound like a bug in Apple's implementation, e.g., TEKs somehow matched to wrong validity periods. There seems to be very little wiggle room in the spec around this stuff and we both seem to have interpreted it the same way

**Comment by marcdownie** [comment]
Ok! 13.5 beta 4 has improved the situation dramatically. We'll do another two days / TEKs worth of runs to make sure there aren't any RPI's we've captured that can't be generated by our code, but already I can tell that Apple's code (and your code, and my code) are much closer. The rolling interval seems random between 20 and 30 mins, so only 1/3 of the potential 144 RPIs will be seen. 

I'll close this after a complete days worth of keys has been seen and verified.

**Comment by HellPie** [comment]
Has this been tested with the first public beta of Google Play Services (version 20.18.16, released 11th of May)? They included a very work in progress implementation. It shows a menu entry stating 1 app in the "Google" system settings main patge and Exposure Notification is allegedly enabled according to the description but the settings page has an empty layout file. There is code in the expected package where the API should be located, it looks mostly functional and it taps into the existing "Nearby" code which is also part of the more broad geofencing code, the service itself doesn't seem to leak data outside of its own area of competence but the generic code they rely on most likely does so I'm afraid of finding out how little privacy there really is if I keep digging into the implementation.

I'm going to work on the new beta (20.18.16, released yesterday, the 13th of May) now, hopefully learning some more about it as the code is still highly obfuscated and my PC doesn't have enough RAM (16GB total, I need MUCH more) for JaDx to handle decompilation and renaming of obfuscated code for readability.

**Comment by oseiskar** [comment]
@HellPie I haven't tested with the recent Google Play Services yet either

**Comment by HellPie** [comment]
It doesn't look like 20.18.16 has any API Surface changes on the non-obfuscated classes, I'll have to dig into the code to know more but right now I'm more worried that the Google Play Services settings entry reports "1app" in the settings entry description. Considering there is no permission for Exposure Notification access (unlike iOS which requires a specific Entitlement) and that a BroadcastReceiver in Android can be registered programmatically without specifying it in AndroidManifest, I'm currently less worried about the possibility of the API not working, since it probably doesn't fully work yet and I can't test it (I don't have a Raspberry Pi with BLE and I don't know how to code an UWP app for my Windows 10 laptop who does support it) and more worried that Google might be playing some trick to try and act smarter than they are by registering a BroadcastReceiver to the API for either additional logging or general anti-privacy Google-ish stuff to make the API seem perfectly fine but still get the data they constantly crave for using one of their literally 100s of system apps instead.

**Comment by oseiskar** [comment]
Update: Both the Linux and Android versions of this code can verifiably receive GAEN traffic
